server:
   port: {{furmsServer.port}}
   address: {{furmsServer.host}}
   ssl:
      key-store-type: {{furmsServer.pki.keyStore.type}}
      key-store-password: {{furmsServer.pki.keyStore.password}}
      key-store: ./{{keystoreTargetFileName}}
      key-password: ${server.ssl.key-store-password}
      enabled-protocols: TLSv1.2, TLSv1.3

furms:
   unity:
      url: https://{{unity.advertisedHost}}
      ssl:
         trust-store: file:./{{truststoreTargetFileName}}
         trust-store-password: {{trustStore.password}}

      admin-url: https://{{unity.host}}:{{unity.port}}/rest-admin/v1
      admin-user: {{unityApiClientUsername}}
      admin-password: {{unityApiClientPassword}}
      oAuth:
         clientId: {{unityOauthClientUsername}}
         clientSecret: {{unityOauthClientPassword}}
   url: https://{{furmsServer.advertisedHost}}
   psk:
      centralIdPUser: {{furmsServer.preSharedKeys.cIdP.username}}
      centralIdPSecret: {{furmsServer.preSharedKeys.cIdP.password}}
   front:
      language: en

spring:
   datasource:
      url: jdbc:postgresql://{{furmsServer.db.host}}/{{furmsServer.db.dbName}}
      username: {{furmsServer.db.username}}
      password: {{furmsServer.db.password}}
      driver-class-name: org.postgresql.Driver

logging:
    config: ./logback.xml
