server:
   port: {{furmsServer.port}}
   ssl:
      key-store: ./keystore.p12
      key-store-type: PKCS12
      key-store-password: {{furmsServer.pki.credentialsPassword}}
      key-password: ${server.ssl.key-store-password}
      enabled-protocols: TLSv1.2

furms:
   unity:
      url: https://{{unity.advertisedHost}}
      ssl:
         trust-store: file:./demoTruststore.jks
         trust-store-password: {{furmsServer.pki.truststoresPassword}}

      admin-url: https://{{unity.host}}:{{unity.port}}/rest-admin/v1
      admin-user: {{unity.apiClient.username}}
      admin-password: {{unity.apiClient.password}}
      oAuth:
         clientId: {{unity.oauthClient.username}}
         clientSecret: {{unity.oauthClient.password}}
   url: https://{{furmsServer.advertisedHost}}
   language: en

spring:
   datasource:
      url: jdbc:h2:file:./db/furms;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      driver-class-name: org.h2.Driver

logging:
    config: ./logback.xml
