installDir: "{{inventory_dir}}/services"
furmsVersion: 1.0.0

backupDirectory:         -- set -- me --

trustStore:
  file:                  -- set -- me --
  password:              -- set -- me --

unity:
  host: localhost
  port: 2443
  advertisedHost:        -- set -- me --
  initialAdminUsername:  -- set -- me --
  initialAdminPassword:  -- set -- me --
  proxyCount:            -- set -- me --

  pki:
    keyStore:
      file:              -- set -- me --
      type:              -- set -- me --
      password:          -- set -- me --

  db:
    host:                -- set -- me --
    dbName:              -- set -- me --
    username:            -- set -- me --
    password:            -- set -- me --

  cIdP:
    clientId:            -- set -- me --
    clientSecret:        -- set -- me --
    discoveryEndpoint:   -- set -- me --

  mail:
    from:                -- set -- me --
    smtp:
      host:              -- set -- me --
      port:              -- set -- me --
      username:          -- set -- me --
      password:          -- set -- me --

  msgTemplates:
    files:               -- set -- me --
    configuration:       -- set -- me --

furmsServer:
  host: localhost
  port: 3443
  advertisedHost:        -- set -- me --

  pki:
    keyStore:
      file:              -- set -- me --
      type:              -- set -- me --
      password:          -- set -- me --

  db:
    host:                -- set -- me --
    dbName:              -- set -- me --
    username:            -- set -- me --
    password:            -- set -- me --

  preSharedKeys:
    cIdP:
      username:          -- set -- me --
      password:          -- set -- me --

  broker:
    host: localhost
    port: 5671
    username:            -- set -- me --
    password:            -- set -- me --
    virtualHost:         -- set -- me --

  ui:
    maxSessionInactivityInSeconds:     -- set -- me --
    secondsBeforeShowingLogoutWarning: -- set -- me --

  layout:
    cssStyle:             -- set -- me --
    panels:
      top:                -- set -- me --
      left:               -- set -- me --
      right:              -- set -- me --
      bottom:             -- set -- me --