currentAppDir: "{{installDir}}/{{installTimestamp}}"
workspaceAppDir: "{{installDir}}/workspace"
runtimeAppDir: "{{installDir}}/current"

truststoreTargetFileName: truststore.jks

unityApiClientUsername: api-admin
unityOauthClientUsername: oauth-client

templateFilesVersion: "{{furmsVersion | regex_search('([0-9]+\\.[0-9]+)')}}"
