currentAppDir: "{{installDir}}/{{installTimestamp}}"
workspaceAppDir: "{{installDir}}/workspace"
runtimeAppDir: "{{installDir}}/current"

truststoreTargetFileName: truststore.jks

unityApiClientUsername: api-admin
unityOauthClientUsername: oauth-client

