currentAppDir: "{{installDir}}/{{installTimestamp}}"
workspaceAppDir: "{{installDir}}/workspace"
runtimeAppDirName: "current"
runtimeAppDir: "{{installDir}}/{{runtimeAppDirName}}"

truststoreTargetFileName: truststore.jks

unityApiClientUsername: api-admin
unityOauthClientUsername: oauth-client

templateFilesVersionSufix: "{{ '-dev' if furmsVersion.endswith('SNAPSHOT') else '' }}"
templateFilesVersionPrefix: "{{furmsVersion | regex_search('([0-9]+\\.[0-9]+)')}}"
templateFilesVersion: "{{templateFilesVersionPrefix}}{{templateFilesVersionSufix}}"
