serviceDir: "furms-server"
serviceVersionedDir: "furms-server-{{furmsServiceVersion}}"
serviceCurrentAppDir: "{{currentAppDir}}/{{serviceDir}}"
serviceRuntimeAppDir: "{{runtimeAppDir}}/{{serviceDir}}"
serviceInstallationDir: "{{currentAppDir}}/{{serviceVersionedDir}}"

serviceCmd: "furms-server-{{furmsServiceVersion}}.jar"
serviceStartCmd: "{{serviceCmd}} start"
serviceStopCmd: "{{serviceCmd}} stop"
serviceURL: "https://{{furmsServer.host}}:{{furmsServer.port}}"
healthCheckPath: "/app-health"
