---
- name: Perform FURMS backup
  hosts: local_only

  tasks:
  - name: "Set timestamp of the backup"
    set_fact:
      now: "{{ lookup('pipe', 'date +%F_%T') + '_v' + furmsVersion }}"

  - name: "Create a backup directory"
    file:
      path: "{{backupDir}}/{{ now }}/"
      state: directory

  - import_tasks: backup-database-task.yml
    vars:
      dumpFileBaseName: furmsDb
      dbName: "{{furmsServer.db.dbName}}"
      dbHost: "{{furmsServer.db.host}}"
      dbUsername: "{{furmsServer.db.username}}"
      dbPassword: "{{furmsServer.db.password}}"


  - import_tasks: backup-database-task.yml
    vars:
      dumpFileBaseName: unityDb
      dbName: "{{unity.db.dbName}}"
      dbHost: "{{unity.db.host}}"
      dbUsername: "{{unity.db.username}}"
      dbPassword: "{{unity.db.password}}"

  - set_fact:
      filesToArchive:
      - "{{inventory_dir}}/inventory"
      - "{{inventory_dir}}/group_vars"
      - "{{trustStore.file}}"
      - "{{unity.pki.keyStore.file}}"
      - "{{furmsServer.pki.keyStore.file}}"

  - set_fact:
      layout: "{{ furmsServer.layout | default({}) }}"
  - set_fact:
      panels: "{{ layout.panels | default({}) }}"
  - set_fact:
      cssStyle: "{{ layout.cssStyle if layout.cssStyle is defined else '' }}"
      topPanel: "{{ panels.top if panels.top is defined else '' }}"
      leftPanel: "{{ panels.left if panels.left is defined else '' }}"
      rightPanel: "{{ panels.right if panels.right is defined else '' }}"
      bottomPanel: "{{ panels.bottom if panels.bottom is defined else '' }}"
  - set_fact:
      msgTemplates: "{{ unity.msgTemplates | default({}) }}"
  - set_fact:
      msgTemplatesFiles: "{{ msgTemplates.files if msgTemplates.files is defined else '' }}"
      msgTemplatesConfig: "{{ msgTemplates.configuration if msgTemplates.configuration is defined else '' }}"
  - set_fact:
      filesToArchive: "{{ filesToArchive + [item] }}"
    with_items: "{{ [cssStyle, topPanel, leftPanel, rightPanel, bottomPanel, msgTemplatesFiles, msgTemplatesConfig] }}"
    when: item != ''


  - name: Backup Ansible configuration
    archive:
      path: "{{ filesToArchive }}"
      dest: "{{backupDir}}/{{now}}/ansible_config.tar.gz"