---
- name: Initialize installation timestamp
  hosts: local_only
  tasks:
  - name: Get installation timestamp
    shell: "date +%Y%m%d-%H%M%S"
    register: installTimestampResult
  - name: Persist installation timestamp
    set_fact:
      installTimestamp: "{{ installTimestampResult.stdout }}"

##################################################################################
# The following tasks either generates or restores the passwords form the local
# management host files. The same password is used across the hosts, and it must
# survive consequtive installations. Files are stored in {{inventory_dir}}/group_vars 
# directory.
##################################################################################
- import_playbook: get-stored-password.yml
  vars:
    target: "unityApiClientPassword"
- name: Initialize unityApiClientPassword
  hosts: local_only
  tasks:
  - name: Persist unityApiClientPassword
    set_fact:
      unityApiClientPassword: "{{targetPassword}}"

- import_playbook: get-stored-password.yml
  vars:
    target: "unityOauthClientPassword"
- name: Initialize unityOauthClientPassword
  hosts: local_only
  tasks:
  - name: Persist unityOauthClientPassword
    set_fact:
      unityOauthClientPassword: "{{targetPassword}}"

#########################################
# Installation process
#########################################
- import_playbook: setup-app-dirs.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"
  
- import_playbook: setup-unity.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"
  
- import_playbook: setup-furms-server.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"

- import_playbook: setup-app-symlink.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"

- import_playbook: setup-configs.yml
  vars:
    unityApiClientPassword: "{{hostvars['localhost']['unityApiClientPassword']}}"
    unityOauthClientPassword: "{{hostvars['localhost']['unityOauthClientPassword']}}"

- import_playbook: setup-certs.yml
