---
- name: Initialize installation timestamp
  hosts: local_only
  tasks:
  - name: Get installation timestamp
    shell: "date +%Y%m%d-%H%M%S"
    register: installTimestampResult
  - name: Persist installation timestamp
    set_fact:
      installTimestamp: "{{ installTimestampResult.stdout }}"

- import_playbook: setup-passwords.yml

- import_playbook: setup-app-dirs.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"
  
- import_playbook: setup-unity.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"
  
- import_playbook: setup-furms-server.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"

- import_playbook: setup-app-symlink.yml
  vars:
    installTimestamp: "{{hostvars['localhost']['installTimestamp']}}"

- import_playbook: setup-configs.yml
  vars:
    unityApiClientPassword: "{{hostvars['localhost']['unityApiClientPassword']}}"
    unityOauthClientPassword: "{{hostvars['localhost']['unityOauthClientPassword']}}"

- import_playbook: setup-certs.yml
