---
##################################################################################
# The following tasks either generates or restores the passwords form the local
# management host files. The same password is used across the hosts, and it must
# survive consequtive installations. Files are stored in {{inventory_dir}}/group_vars 
# directory.
##################################################################################
- import_playbook: get-stored-password.yml
  vars:
    target: "unityApiClientPassword"
- name: Initialize unityApiClientPassword
  hosts: local_only
  tasks:
  - name: Persist unityApiClientPassword
    set_fact:
      unityApiClientPassword: "{{targetPassword}}"

- import_playbook: get-stored-password.yml
  vars:
    target: "unityOauthClientPassword"
- name: Initialize unityOauthClientPassword
  hosts: local_only
  tasks:
  - name: Persist unityOauthClientPassword
    set_fact:
      unityOauthClientPassword: "{{targetPassword}}"