---
- name: Check type of deployment
  hosts: furms_server
  tasks:
  - set_fact: 
      isSnapshot: "{{furmsServiceVersion.endswith('SNAPSHOT')}}"

- name: Determine FURMS deliverables
  gather_facts: no
  hosts: furms_server
  tasks:
  - import_tasks: set-facts-for-snapshot.yml
    when: isSnapshot

  - import_tasks: set-facts-for-release.yml
    when: not isSnapshot

  - import_tasks: setup-server.yml

  - name: install identity config file
    copy:
      src: "files/furms-app.conf"
      dest: "{{serviceCurrentAppDir}}/{{furmsDeliverableBaseName}}.conf"

  - name: remove javadoc jar
    file:
      state: absent
      path: "{{serviceCurrentAppDir}}/{{furmsDeliverableBaseName}}-javadoc.jar"

  - name: remove sources jar
    file:
      state: absent
      path: "{{serviceCurrentAppDir}}/{{furmsDeliverableBaseName}}-sources.jar"



  