---
- name: Install config files to servers
  hosts: "{{targetHosts if targetHosts is defined else 'all_servers'}}"
  tasks:
  - name: Include version vars
    include_vars:
      file: "files/config_templates/{{templateFilesVersion}}/version_vars.yml"

  - name: create directories
    file:
      state: directory
      path: "{{serviceRuntimeAppDir}}/{{item.path}}"
      mode: '0750'
    with_filetree:
      - "files/config_templates/{{templateFilesVersion}}/{{serviceDir}}/"
    when: item.state == 'directory'

  - name: check files
    stat:
      path: "{{item.src}}"
    with_filetree:
      - "files/config_templates/{{templateFilesVersion}}/{{serviceDir}}/"
    when: item.state == 'file'
    register: files_stats

  - name: install and filtered configs
    template:
      src: "{{item.item.src}}"
      dest: "{{serviceRuntimeAppDir}}/{{item.item.path}}"
    with_items: "{{ files_stats.results }}"
    when: 
      - "'stat' in item"
      - item.stat.charset != 'binary'
      - not item.stat.path.endswith('.pem')
      - not item.stat.path.endswith('log4j2.xml')

  - name: install configs
    copy:
      src: "{{item.item.src}}"
      dest: "{{serviceRuntimeAppDir}}/{{item.item.path}}"
    with_items: "{{ files_stats.results }}"
    when:
      - "'stat' in item"
      - item.stat.charset == 'binary' or item.stat.path.endswith('.pem') or item.stat.path.endswith('log4j2.xml')