---
- name: Setup Unity-IdM registration forms
  gather_facts: no
  hosts: unity
  tasks:
  - name: create registratoin forms directory
    file:
      state: directory
      path: "{{registrationFormsDir}}"
      mode: '0750'
  - name: Setup registration forms
    copy:
      src: "{{unity.registrationFormsFile}}"
      dest: "{{registrationFormsDir}}/registrationForms.json"
    when: unity.registrationFormsFile is defined


