---
- name: Check type of deployment
  hosts: furms_server
  tasks:
  - include_vars:
      file: "files/config_templates/{{furmsVersion}}/version_vars.yml"
  - set_fact: 
      isSnapshot: "{{furmsServiceVersion.endswith('SNAPSHOT')}}"

- name: Determine FURMS deliverables
  gather_facts: no
  hosts: furms_server
  tasks:
  - import_tasks: set-facts-for-snapshot.yml
    when: isSnapshot

  - import_tasks: set-facts-for-release.yml
    when: not isSnapshot

  - import_tasks: setup-server.yml

  - 

  